title: Data to Discovery
description: Data to Discovery is a fortnightly seminar series held at the Informatics Forum on Fridays
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

github:
  is_project_page: false
  baseurl: /
